---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by admin.
--- DateTime: 2022/10/12 14:16
---
-- nil
print()
print(a1)
a1 = 10
print(a1)

-- type
print()
print(a2, type(a2))
print(print, type(print))
-- print(print()) -- two empty line, not print nil
-- print(type(print())) -- error
a2 = 0
a2 = print()
print(a2) -- print nil
a2 = print
print(a2, (type(a2)))

-- tf
print()
a2 = nil
print(a2 == true, a2 and true)
a2 = 0
print(a2 == true, a2 and true)
a2 = ""
print(a2 == true, a2 and true)

-- str
print()
s1 = [[
line 1
line 2
]]
print(s1)
s1 = [=[
a=b[c[i]]
]=]
print(s1)
print("left" .. "right", 0 .. "right", #"right")

-- table
print()
t = {}
t["x"] = "key is \"x\""
t[10] = "key is 10";
print(t.x, t["x"], t[10], t["y"])
t = {}
t[100] = 1
print(#t, table.maxn(t))
t = {}
t[0] = 1
print(#t, table.maxn(t))
t = {}
t[1] = 1
print(#t, table.maxn(t))
t = {
    a = "\"a\"",
    [0] = "0",
    ["0"] = "\"0\""
}
t = { 1, 2, 3, "a", "b", "c" }

-- repeat and local
print()
do
    local last = 0;
    repeat
        local curr = last + 1
        last = curr
    until curr == 5 -- `curr` can be visited here
end

-- for
print()
do
    local i = 5
    for i = 1, 1 do
        print(i)
    end
    print(i) -- not that i
end

-- fori and forp
print()
do
    t = {
        a = "\"a\"",
        [0] = "0",
        ["0"] = "\"0\"",
        "1",
        "2"
    }
    for k, v in pairs(t) do
        print(k, v)
    end
    print()
    for i, v in ipairs(t) do
        print(i, v)
    end
end

-- iter and nil
print()
do
    t = { 1, nil, 2 }
    print("size is", #t)
    for i, v in ipairs(t) do
        print(i, v)
    end
end
